// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/new-features/CalmDown.tsx": () => import("../components/mockups/new-features/CalmDown.tsx"),
  "./components/mockups/new-features/FeelingsPicker.tsx": () => import("../components/mockups/new-features/FeelingsPicker.tsx"),
  "./components/mockups/new-features/StoryChoice.tsx": () => import("../components/mockups/new-features/StoryChoice.tsx"),
  "./components/mockups/new-features/VoiceRetell.tsx": () => import("../components/mockups/new-features/VoiceRetell.tsx"),
  "./components/mockups/storytime-variants/Dreamland.tsx": () => import("../components/mockups/storytime-variants/Dreamland.tsx"),
  "./components/mockups/storytime-variants/Rainbow.tsx": () => import("../components/mockups/storytime-variants/Rainbow.tsx"),
  "./components/mockups/storytime-variants/Storybook.tsx": () => import("../components/mockups/storytime-variants/Storybook.tsx")
};
